name: Test Builder for Go 1.24 Windows ARM32

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/build-go-1-24-windows-arm32.yml
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - .github/workflows/build-go-1-24-windows-arm32.yml

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        goos: [windows]
        goarch: [arm]
        goarm: [7]
      fail-fast: false

    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOARM: ${{ matrix.goarm }}
      CGO_ENABLED: 0
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Show workflow information
        run: |
          [ -n "$_NAME" ] || _NAME="$GOOS-$GOARCH"
          echo "GOOS: $GOOS, GOARCH: $GOARCH, RELEASE_NAME: $_NAME"
          echo "ASSET_NAME=$_NAME" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true

      - name: Get project dependencies
        run: go mod download
      
      - name: Build Xray
        run: |
          mkdir -p build_assets
          COMMID=$(git describe --always --dirty)
          if [[ ${GOOS} == 'windows' ]]; then
            go build -buildvcs=false -o build_assets/xray.exe -trimpath -ldflags "-X github.com/xtls/xray-core/core.build=${COMMID} -s -w -buildid=" -v ./main
            go build -buildvcs=false -o build_assets/wxray.exe -trimpath -ldflags "-H windowsgui -X github.com/xtls/xray-core/core.build=${COMMID} -s -w -buildid=" -v ./main
          else
            go build -buildvcs=false -o build_assets/xray -trimpath -ldflags "-X github.com/xtls/xray-core/core.build=${COMMID} -s -w -buildid=" -v ./main
          fi

      - name: Change the name
        run: |
          mv build_assets Xray-${{ env.ASSET_NAME }}

      - name: Upload files to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Xray-${{ env.ASSET_NAME }}
          path: |
            ./Xray-${{ env.ASSET_NAME }}/*
