name: Enhanced Builder for other architecture
# For OS and architecture comnbinations that supported by official reposity with only tweaked changes.
# Build 20261009

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - builder-enhance
    paths:
      - ".github/workflows/builder-enh-others.yml"
jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          # BEGIN ARM64 Specified
          - goos: darwin
            goarch: arm64
            goarm64: v8.6
          - goos: windows
            goarch: arm64
            goarm64: v8.7
          # END ARM64 Specified
      fail-fast: false

    runs-on: windows-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOAMD64: ${{ matrix.goamd64 }}
      GOARM64: ${{ matrix.goarm64 }}
      GORISCV64: ${{ matrix.goriscv64 }}
      GOPPC64: ${{ matrix.goppc64 }}
      CGO_ENABLED: 0
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v7
        with:
          ref: main

      - name: Show workflow information
        shell: pwsh
        run: |
          $name = "$env:GOOS-$env:GOARCH$env:GOAMD64$env:GOARM64$env:GORISCV64$env:GOPPC64"
          Write-Host "GOOS: $env:GOOS, GOARCH: $env:GOARCH, GOAMD64: $env:GOAMD64, GOARM64: $env:GOARM64, GORISCV64: $env:GORISCV64, GOPPC64: $env:GOPPC64, RELEASE_NAME: $name"
          Add-Content -Path $env:GITHUB_ENV -Value "ASSET_NAME=$name" -Encoding utf8

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Get project dependencies
        shell: pwsh
        run: go mod download
      
      - name: Build Xray
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path .\build_assets -Force | Out-Null
          $commit = (git describe --always --dirty).Trim()
          if ($env:GOOS -eq 'windows') {
            Write-Host 'Building Xray for Windows...'
            go build -o build_assets\xray.exe -trimpath -buildvcs=false -gcflags 'all=-l=4' -ldflags "-X github.com/xtls/xray-core/core.build=$commit -s -w -buildid=" -v .\main
            # go build -o build_assets\wxray.exe -trimpath -buildvcs=false -gcflags 'all=-l=4' -ldflags "-H windowsgui -X github.com/xtls/xray-core/core.build=$commit -s -w -buildid=" -v .\main
          } else {
            Write-Host 'Building Xray...'
            go build -o build_assets\xray -trimpath -buildvcs=false -gcflags 'all=-l=4' -ldflags "-X github.com/xtls/xray-core/core.build=$commit -s -w -buildid=" -v .\main
          }

      - name: Copy README.md & LICENSE
        shell: pwsh
        run: |
          Copy-Item -Path "$env:GITHUB_WORKSPACE\README.md" -Destination .\build_assets\README.md
          Copy-Item -Path "$env:GITHUB_WORKSPACE\LICENSE" -Destination .\build_assets\LICENSE

      - name: Create ZIP archive
        if: github.event_name == 'release'
        shell: pwsh
        run: |
          Push-Location build_assets
          $timestamp = [datetime]::new((Get-Date).Year, 1, 1, 0, 0, 0)
          Get-ChildItem -File | ForEach-Object { $_.LastWriteTime = $timestamp }
          7z a -tzip -mx=9 "..\Xray-$env:ASSET_NAME.zip" .\*
          Pop-Location
        # $file = ".\Xray-$env:ASSET_NAME.zip"
        # $dgst = "$file.dgst"
        # foreach ($method in @('SHA256', 'SHA512')) {
        #   $hash = Get-FileHash -Algorithm $method -Path $file
        #   "$($hash.Algorithm) $($hash.Hash) $file" | Add-Content -Path $dgst
        # }

      - name: Upload files to Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Xray-${{ env.ASSET_NAME }}
          path: |
            ./build_assets/*

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./Xray-${{ env.ASSET_NAME }}.zip*
          tag: ${{ github.ref }}
          file_glob: true
