name: Scheduled assets update

# NOTE: This Github Actions is required by other actions, for preparing other packaging assets in a
#       routine manner, for example: GeoIP/GeoSite.
#       Currently updating:
#       - Geodat (GeoIP/Geosite)
#       - Wintun (wintun.dll)

on:
  workflow_dispatch:
  schedule:
    # Update GeoData on every day (22:30 UTC)
    - cron: "30 22 * * *"
  push:
    # Prevent triggering update request storm
    paths:
      - ".github/workflows/scheduled-assets-update.yml"
  pull_request:
    # Prevent triggering update request storm
    paths:
      - ".github/workflows/scheduled-assets-update.yml"

jobs:
  geodat:
    if: github.event.schedule == '30 22 * * *' || github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Restore Geodat Cache
        uses: actions/cache/restore@v5
        with:
          path: resources
          key: xray-geodat-

      - name: Update Geodat
        id: update
        uses: nick-fields/retry@v4
        with:
          timeout_minutes: 60
          retry_wait_seconds: 60
          max_attempts: 60
          command: |
            [ -d 'resources' ] || mkdir resources
            LIST=('Loyalsoldier v2ray-rules-dat geoip geoip' 'Loyalsoldier v2ray-rules-dat geosite geosite')
            for i in "${LIST[@]}"
            do
              INFO=($(echo $i | awk 'BEGIN{FS=" ";OFS=" "} {print $1,$2,$3,$4}'))
              FILE_NAME="${INFO[3]}.dat"
              echo -e "Verifying HASH key..."
              HASH="$(curl -sL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://raw.githubusercontent.com/${INFO[0]}/${INFO[1]}/release/${INFO[2]}.dat.sha256sum" | awk -F ' ' '{print $1}')"
              if [ -s "./resources/${FILE_NAME}" ] && [ "$(sha256sum "./resources/${FILE_NAME}" | awk -F ' ' '{print $1}')" == "${HASH}" ]; then
                  continue
              else
                  echo -e "Downloading https://raw.githubusercontent.com/${INFO[0]}/${INFO[1]}/release/${INFO[2]}.dat..."
                  curl -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://raw.githubusercontent.com/${INFO[0]}/${INFO[1]}/release/${INFO[2]}.dat" -o ./resources/${FILE_NAME}
                  echo -e "Verifying HASH key..."
                  [ "$(sha256sum "./resources/${FILE_NAME}" | awk -F ' ' '{print $1}')" == "${HASH}" ] || { echo -e "The HASH key of ${FILE_NAME} does not match cloud one."; exit 1; }
                  echo "unhit=true" >> $GITHUB_OUTPUT
              fi
            done

      - name: Save Geodat Cache
        uses: actions/cache/save@v5
        if: ${{ steps.update.outputs.unhit }}
        with:
          path: resources
          key: xray-geodat-${{ github.sha }}-${{ github.run_number }}

  wintun:
    if: github.event.schedule == '30 22 * * *' || github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      ASSETVER: 0.14.1
      ASSETHASH: 07c256185d6ee3652e09fa55c0b673e2624b565e02c4b9091c79ca7d2f24ef51
    steps:
      - name: Restore Wintun Cache
        uses: actions/cache/restore@v5
        with:
          path: resources
          key: xray-wintun-

      - name: Force downloading if run manually or on file update
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
        run: |
          echo "FORCE_UPDATE=true" >> $GITHUB_ENV

      - name: Update Wintun
        id: update
        uses: nick-fields/retry@v4
        with:
          timeout_minutes: 60
          retry_wait_seconds: 60
          max_attempts: 60
          command: |
            [ -d 'resources' ] || mkdir resources
            LIST=('amd64' 'x86' 'arm64')
            for ARCHITECTURE in "${LIST[@]}"
            do
              FILE_PATH="resources/wintun/bin/${ARCHITECTURE}/wintun.dll"
              echo -e "Checking if wintun.dll for ${ARCHITECTURE} exists..."
              if [ -s "./resources/wintun/bin/${ARCHITECTURE}/wintun.dll" ]; then
                  echo -e "wintun.dll for ${ARCHITECTURE} exists"
                  continue
              else
                  echo -e "wintun.dll for ${ARCHITECTURE} is missing"
                  missing=true
              fi
            done
            if [ -s "./resources/wintun/LICENSE.txt" ]; then
              echo -e "LICENSE for Wintun exists"
            else
              echo -e "LICENSE for Wintun is missing"
              missing=true
            fi
            if [[ -v FORCE_UPDATE ]]; then
              missing=true
            fi
            if [[ "$missing" == true ]]; then
              FILENAME=wintun.zip
              DOWNLOAD_FILE=wintun-${ASSETVER}.zip
              echo -e "Downloading https://www.wintun.net/builds/${DOWNLOAD_FILE}..."
              curl -L "https://www.wintun.net/builds/${DOWNLOAD_FILE}" -o "${FILENAME}"
              if [[ "$(sha256sum "./${FILENAME}" | awk -F ' ' '{print $1}')" == "${ASSETHASH}" ]]; then
                echo -e "Unpacking wintun..."
                unzip -u ${FILENAME} -d resources/
                echo "unhit=true" >> $GITHUB_OUTPUT
              else
                echo -e "Digest of ${FILENAME} mismatch."
                exit 1
              fi
            fi

      - name: Save Wintun Cache
        uses: actions/cache/save@v5
        if: ${{ steps.update.outputs.unhit }}
        with:
          path: resources
          key: xray-wintun-${{ github.sha }}-${{ github.run_number }}

  windivert:
    if: github.event.schedule == '30 22 * * *' || github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      ASSETVER: 2.2.2
      ASSETHASH: 63cb41763bb4b20f600b6de04e991a9c2be73279e317d4d82f237b150c5f3f15
    steps:
      - name: Restore WinDivert Cache
        uses: actions/cache/restore@v5
        with:
          path: resources
          key: xray-windivert-

      - name: Force downloading if run manually or on file update
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
        run: |
          echo "FORCE_UPDATE=true" >> $GITHUB_ENV

      - name: Update WinDivert
        id: update
        uses: nick-fields/retry@v4
        with:
          timeout_minutes: 60
          retry_wait_seconds: 60
          max_attempts: 60
          command: |
            [ -d 'resources' ] || mkdir resources
            LIST=('x64 64' 'x86 32')
            for ARCHITECTURE in "${LIST[@]}"
            do
              INFO=($(echo $i | awk 'BEGIN{FS=" ";OFS=" "} {print $1,$2}'))
              FILE_PATH="resources/windivert/${INFO[0]}/WinDivert.dll"
              echo -e "Checking if WinDivert.dll for ${INFO[0]} exists..."
              if [ -s "./resources/windivert/${INFO[0]}/WinDivert.dll" ]; then
                  echo -e "WinDivert.dll for ${INFO[0]} exists"
                  continue
              else
                  echo -e "WinDivert.dll for ${INFO[0]} is missing"
                  missing=true
              fi
              echo -e "Checking if WinDivert${INFO[1]}.sys for ${INFO[0]} exists..."
              if [ -s "./resources/windivert/${INFO[0]}/WinDivert${INFO[1]}.sys" ]; then
                  echo -e "WinDivert${INFO[1]}.sys for ${INFO[0]} exists"
                  continue
              else
                  echo -e "WinDivert${INFO[1]}.sys for ${INFO[0]} is missing"
                  missing=true
              fi
            done
            if [[ -v FORCE_UPDATE ]]; then
              missing=true
            fi
            if [[ "$missing" == true ]]; then
              FILENAME=WinDivert-${ASSETVER}-A.zip
              DOWNLOAD_FILE=${FILENAME}
              echo -e "Downloading https://github.com/basil00/WinDivert/releases/download/v${ASSETVER}/${DOWNLOAD_FILE}..."
              curl -L "https://github.com/basil00/WinDivert/releases/download/v${ASSETVER}/${DOWNLOAD_FILE}" -o "${FILENAME}"
              if [[ "$(sha256sum "./${FILENAME}" | awk -F ' ' '{print $1}')" == "${ASSETHASH}" ]]; then
                echo -e "Unpacking WinDivert..."
                unzip -u ${FILENAME} -d ./
                mkdir resources/windivert
                mkdir resources/windivert/x64
                mv ${FILENAME}/x64/*.dll resources/windivert/x64
                mv ${FILENAME}/x64/*.sys resources/windivert/x64
                mkdir resources/windivert/x86
                mv ${FILENAME}/x86/*.dll resources/windivert/x86
                mv ${FILENAME}/x86/*.sys resources/windivert/x86
                echo -e "Downloading License..."
                curl -L "https://www.gnu.org/licenses/gpl-3.0.txt" -o "LICENSE-WINDIVERT.txt"
                curl -L "https://www.gnu.org/licenses/lgpl-3.0.txt" -o "LICENSE-WINDIVERT.LESSER.txt"
                cp LICENSE-*.txt resources/windivert
                echo "unhit=true" >> $GITHUB_OUTPUT
              else
                echo -e "Digest of ${FILENAME} mismatch."
                exit 1
              fi
            fi

      - name: Save WinDivert Cache
        uses: actions/cache/save@v5
        if: ${{ steps.update.outputs.unhit }}
        with:
          path: resources
          key: xray-windivert-${{ github.sha }}-${{ github.run_number }}
